language: node_js
node_js:
  - "6.9"
before_script: 
  - npm install -g --silent @angular/cli@1.2.6
  - npm install -g --silent yarn
script:
  - cd server && yarn install && yarn run gulp build-all && tsc && cd ../AzureFunctions.AngularClient && yarn install && ng build -prod 