# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - __sitename__

on:
  push:
    branches:
      - __branch__
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '__runtimeversion__'

      - name: Build using AppService-Build
        uses: azure/appservice-build@v2
        with:
          platform: python
          platform-version: '__runtimeversion__'

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: '__sitename__'
          slot-name: '__slotname__'
          publish-profile: \${{ secrets.__secretname__ }}
